name: Release

on:
  push:
    tags:
      - '**'

env:
  NAME: surface-ath10k-firmware-override
  SCRIPTS: ./.github/scripts
  BRANCH_STAGING: u/staging

jobs:
  build-arch:
    name: Build Arch Linux Package
    runs-on: ubuntu-latest
    container: qzed/archlinux
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: $SCRIPTS/pkg-arch.sh install

    - name: Build package
      run: $SCRIPTS/pkg-arch.sh build

    - name: Sign package
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: $SCRIPTS/pkg-arch.sh sign

    - name: Prepare release
      run: $SCRIPTS/pkg-arch.sh release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: arch-latest
        path: release

  build-deb:
    name: Build Debian Package
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: $SCRIPTS/pkg-debian.sh install

    - name: Build package
      run: $SCRIPTS/pkg-debian.sh build

    - name: Sign package
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: $SCRIPTS/pkg-debian.sh sign

    - name: Prepare release
      run: $SCRIPTS/pkg-debian.sh release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: debian-latest
        path: release

  build-f35:
    name: Build Fedora 35 package
    runs-on: ubuntu-latest
    container:
      image: fedora:35
      options: --security-opt seccomp=unconfined
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: $SCRIPTS/pkg-fedora.sh install

    - name: Build package
      run: $SCRIPTS/pkg-fedora.sh build

    - name: Sign packages
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: $SCRIPTS/pkg-fedora.sh sign

    - name: Prepare release
      run: $SCRIPTS/pkg-fedora.sh release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fedora-35-latest
        path: release

  build-f34:
    name: Build Fedora 34 package
    runs-on: ubuntu-latest
    container: fedora:34
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: $SCRIPTS/pkg-fedora.sh install

    - name: Build package
      run: $SCRIPTS/pkg-fedora.sh build

    - name: Sign packages
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: $SCRIPTS/pkg-fedora.sh sign

    - name: Prepare release
      run: $SCRIPTS/pkg-fedora.sh release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fedora-34-latest
        path: release

  release:
    name: Publish release
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    needs: [build-deb, build-arch, build-f35, build-f34]
    runs-on: ubuntu-latest
    steps:
    - name: Download Debian artifacts
      uses: actions/download-artifact@v1
      with:
        name: debian-latest

    - name: Download Arch Linux artifacts
      uses: actions/download-artifact@v1
      with:
        name: arch-latest

    - name: Download Fedora 35 artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-35-latest

    - name: Download Fedora 34 artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-34-latest

    - name: Upload assets
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*-latest/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  repo-arch:
    name: Update Arch Linux package repository
    needs: [release]
    runs-on: ubuntu-latest
    container: qzed/archlinux
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: arch-latest

    - name: Update repository
      env:
        SURFACEBOT_TOKEN: ${{ secrets.SURFACE_BOT_TOKEN }}
        GIT_REF: ${{ github.ref }}
      run: $SCRIPTS/repo-arch.sh $NAME

  repo-deb:
    name: Update Debian package repository
    needs: [release]
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: debian-latest

    - name: Update repository
      env:
        SURFACEBOT_TOKEN: ${{ secrets.SURFACE_BOT_TOKEN }}
        GIT_REF: ${{ github.ref }}
      run: $SCRIPTS/repo-debian.sh $NAME

  repo-f35:
    name: Update Fedora 35 package repository
    needs: [release]
    runs-on: ubuntu-latest
    container:
      image: fedora:35
      options: --security-opt seccomp=unconfined
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-35-latest

    - name: Update repository
      env:
        SURFACEBOT_TOKEN: ${{ secrets.SURFACE_BOT_TOKEN }}
        GIT_REF: ${{ github.ref }}
      run: $SCRIPTS/repo-fedora.sh $NAME 35

  repo-f34:
    name: Update Fedora 34 package repository
    needs: [release]
    runs-on: ubuntu-latest
    container: fedora:34
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-34-latest

    - name: Update repository
      env:
        SURFACEBOT_TOKEN: ${{ secrets.SURFACE_BOT_TOKEN }}
        GIT_REF: ${{ github.ref }}
      run: $SCRIPTS/repo-fedora.sh $NAME 34
